import numpy as np
import torch as torch
import matplotlib.pyplot as plt
import os
import seaborn as sns
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

df_bi=torch.load("D:\\ivim_pth\\parameters\\"+r"df_bi.pth")
df_tri=torch.load("D:\\ivim_pth\\parameters\\"+r"df_tri.pth")

plt.rc('font',family='Times New Roman')
plt.figure(figsize=(20,10))
plt.subplot(2,3,1)
plt.xticks(fontsize=20)
plt.yticks(np.arange(-10, 10, 5)/10000,fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Dslow",hue="algorithm",data=df_bi,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,2)
plt.xticks(fontsize=20)
plt.yticks(np.arange(-6, 6, 2)/100,fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Dfast",hue="algorithm",data=df_bi,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,3)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Dvfast",hue="algorithm",data=df_bi,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,4)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Fslow",hue="algorithm",data=df_bi,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,5)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Ffast",hue="algorithm",data=df_bi,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,6)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Fvfast",hue="algorithm",data=df_bi,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplots_adjust(wspace =0.35, hspace =0.2)
plt.savefig(r'D:\ivim_pth\png\\simulation_boxplot_bi.png' , dpi = 800)
plt.show()

##

plt.rc('font',family='Times New Roman')
plt.figure(figsize=(20,10))
plt.subplot(2,3,1)
plt.xticks(fontsize=20)
plt.yticks(np.arange(-20, 20,10)/10000,fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Dslow",hue="algorithm",data=df_tri,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,2)
plt.xticks(fontsize=20)
plt.yticks(np.arange(-8, 32, 8)/100,fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Dfast",hue="algorithm",data=df_tri,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,3)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Dvfast",hue="algorithm",data=df_tri,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.yticks(np.arange(-6, 10, 3)/10)
#plt.ylim((-0.6,0.8))
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,4)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Fslow",hue="algorithm",data=df_tri,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,5)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Ffast",hue="algorithm",data=df_tri,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplot(2,3,6)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.axhline(y=0., color='r', linestyle=':')
sns.boxplot(x="SNR",y="Fvfast",hue="algorithm",data=df_tri,order=[100,50,33,20],whis=1.5,showfliers=False)
plt.xlabel("")
plt.ylabel("")
plt.legend(loc = 'upper left',fontsize=14)

plt.subplots_adjust(wspace =0.35, hspace =0.28)
plt.savefig(r'D:\ivim_pth\png\\simulation_boxplot_tri.png' , dpi = 800)
plt.show()